version: '3.8'

services:
  node_app:
    build: .
    container_name: node_app
    ports:
      - "5000:5000"
    depends_on:
      - postgres_db
    environment:
      DATABASE_URL: "postgresql://user:password@postgres_db:5432/mydb?schema=public"
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]

  postgres_db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
